# Generated by Django 5.0 on 2023-12-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0002_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicles',
            name='price',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='year',
        ),
        migrations.AddField(
            model_name='vehicles',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='distance_covered',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='manufacture_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='mileage',
            field=models.FloatField(null=True),
        ),
    ]
