# Generated by Django 5.0 on 2023-12-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0004_vehicles_best_selling'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='fuel_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
